version: "3"

services:
  redis:
    image: redis:6
    volumes:
      - ./data/redis:/data
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - cakk

networks:
  cakk:
    labels:
      - cakk