name: test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 1. set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 2. grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 3. test with gradle
        run: ./gradlew test
